-- Code generated by `pg2sqlite`. DO NOT EDIT.

CREATE TABLE account_key (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  coin TEXT NOT NULL,
  account TEXT NOT NULL
);

CREATE TABLE composite_example (
  col_a INTEGER NOT NULL,
  col_b INTEGER NOT NULL,
  data TEXT,
  PRIMARY KEY (col_a, col_b)
);

CREATE TABLE pk_only (
  id INTEGER PRIMARY KEY,
  name TEXT
);

CREATE TABLE seed (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  coin TEXT NOT NULL,
  seed TEXT NOT NULL,
  updated_at TEXT DEFAULT (CURRENT_TIMESTAMP)
);
