-- Code generated by `pg2sqlite`. DO NOT EDIT.

CREATE TABLE user_roles (
  user_id INTEGER NOT NULL,
  role_id INTEGER NOT NULL,
  granted_at TEXT DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY (user_id, role_id)
);
