-- Test: ALTER TABLE IDENTITY + PRIMARY KEY to INTEGER PRIMARY KEY AUTOINCREMENT
-- Simulates pg_dump output with separate ALTER TABLE statements

CREATE TABLE seed (
    id smallint NOT NULL,
    coin character varying(255) NOT NULL,
    seed character varying(255) NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.seed ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.seed_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE account_key (
    id bigint NOT NULL,
    coin character varying(255) NOT NULL,
    account character varying(255) NOT NULL
);

ALTER TABLE account_key ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account_key_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Composite PK: should NOT get AUTOINCREMENT
CREATE TABLE composite_example (
    col_a integer NOT NULL,
    col_b integer NOT NULL,
    data text
);

-- PK only, no identity: should get PRIMARY KEY but no AUTOINCREMENT
CREATE TABLE pk_only (
    id bigint NOT NULL,
    name text
);

ALTER TABLE ONLY public.seed
    ADD CONSTRAINT seed_pkey PRIMARY KEY (id);

ALTER TABLE ONLY account_key
    ADD CONSTRAINT account_key_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.composite_example
    ADD CONSTRAINT composite_example_pkey PRIMARY KEY (col_a, col_b);

ALTER TABLE ONLY pk_only
    ADD CONSTRAINT pk_only_pkey PRIMARY KEY (id);
